services:
  - type: web
    plan: free
    name: Channel-Filter-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    repo: https://github.com/ROYAL-JATT/Channel-Filter-Bot
    branch: web
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: CHANNEL
        sync: false
      - key: ADMINS
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DATABASE_URI
        sync: false
      - key : SESSION
        sync: false
